- name: 'Migrating from Java 8 to Java 11'
  trainers: ['hendrik']
  summary: >
    Java 8 is very often used when developing applications. Since the last public release will be 
    published in Jan 2019, the time has come to update to the latest version. Comparing Java 8 and 
    11, many things have changed and migrating to Java 11 is not an easy task. Especially the new 
    module systems brings several challenges.

    During this training course, we will introduce the new features of Java 9 - 11 and we will 
    discuss migration paths for Java 8 based applications and libraries. By testing those paths with 
    specific examples participants will be enabled to overcome the technical hurdles of a migration.

    During the training, we will also clear diverse rumours about Java 11 and we will answer questions 
    like „Do I need to pay for Java?“, „What is OpenJDK?“, „Do I have to update Java every 6 months from 
    now on?“ or „Can I use Java 11 as an LTS version for the next couple of years?“.
  featuredImage: 8-11

- name: 'High performance Web applications with React'
  trainers: ['simon']
  summary: >
    Web development is becoming more and more important in the area of software development. 
    The React library is used in many projects to successfully implement even complex requirements. 
    React promises high-performance applications and at the same time a simple, clearly designed structure. 
    Following this course, participants will learn the basic principles of React.
    
    Practical excercises support the theory taught in this course. The participants will immediately apply 
    the imparted knowledge to specific examples from their everyday work as developers. Thus, the knowledge 
    can be directly transferred to their daily work.
  featuredImage: react

- name: 'Java APIs - the missing manual'
  trainers: ['hendrik']
  summary: >
    Java is a frequently used programming language that offers a wide variety of standard API‘s. 
    Some of them are hardly known and are not used very often - although they offer a high potential 
    for improving API design and the software being developed.

    • When to use the keyword „final“ and how to prevent NullPointerExceptions?

    • How to make software more flexible and modular with SPI or how to address errors within the Stream-API?

    • What is an annotation? How to create annotiations and where to use them?

    Following this training course, participants learn how to use standard APIs in order to write better code.
  featuredImage: apis   

- name: 'JavaFX for business applications'
  trainers: ['hendrik', 'gerrit']
  summary: >
    Following this course, participants will learn how to use the capabilities of JavaFX to design graphical 
    rich user interfaces and also developing long lasting business applications. You will learn the basic 
    terms and advanced concepts of JavaFX.
  featuredImage: fx   

- name: 'JavaFX for sophisticated user interfaces'
  trainers: ['hendrik', 'gerrit']
  summary: >
    Participants will learn how to use the user interface and usability of the various JavaFX APIs to 
    create a modern user experience.
  featuredImage: fx   