- name: 'Migration Java applications from 8 to 11'
  trainers: ['hendrik']
  summary: >
    Viele Entwickler nutzen Java 8 als Basis für ihre Anwendungen. Da im Januar 2019 das letzte 
    öffentliche Release erscheint, wird es Zeit für ein Update auf die aktuelle Java Version. 
    Von Java 8 bis zu Java 11 hat sich einiges getan und eine Migration ist oft keine leichte Aufgabe. 
    Vor allem das neue Modulsystem bietet einige Herausforderungen.
    
    In diesem Training werden die neuen Sprachfeatures von Java 9–11 vorgestellt und Migrationswege 
    von auf Java 8 basierten Anwendungen und Bibliotheken besprochen und anhand von Beispielen selbst 
    ausprobiert. Hierdurch ist jeder Entwickler in der Lage, die technischen Hürden für eine Migration 
    zu überwinden.

    Ebenfalls wird im Training mit verschiedenen Gerüchten über Java 11 aufgeräumt und 
    Fragen beantwortet wie zum Beispiel „Ist Java kostenpflichtig?“,
    „Was ist überhaupt dieses OpenJDK?“, „Muss ich jetzt alle 6 Monate Java updaten?“ 
    oder „Kann ich Java 11 als LTS Version die nächsten Jahre nutzen?“
  featuredImage: TODO

- name: 'Performante Webapplikationen mit React'
  trainers: ['simon']
  summary: >
    Die Web-Entwicklung gewinnt in der Software-Entwicklung immer mehr an Bedeutung. 
    Um auch komplexere Projekte erfolgreich umsetzen zu können kommt in vielen Projekten 
    die React Bibliothek zum Einsatz. React verspricht performante Anwendungen und 
    gleichzeitig einen einfachen, klar strukturierten Aufbau. In die- sem Training 
    lernen Sie die Grundprinzipien von React.

    Praktische Übungen ergänzen dabei die im Kurs vermittelte Theorie. Das gelernte Wissen 
    wenden die Teilnehmer gleich in konkreten Beispielen aus dem Entwickler-alltag an. 
    Die neuen Skills können so direkt auf die eigene Entwicklungsarbeit im Projekt 
    übertragen werden.
  featuredImage: TODO

- name: 'Java - the missing manual'
  trainers: ['hendrik']
  summary: >
    Java wird oft als Programmiersprache eingesetzt und verfügt über eine große Vielfalt von Standard-APIs. 
    Einige der Standard-APIs sind kaum bekannt und werden nicht oft eingesetzt, bieten aber viel Potential, 
    das eigene API Design und die entstehende Software zu verbessern.

    Wann verwendet man das Schlüsselwort „final“, wie verhindert man am besten NullPointerExceptions?

    Wie macht man die Software flexibler und modularer mit SPI, oder wie behandelt man Fehler innerhalb der Stream-API?

    Was sind Annotations? Wie erstellt, und setzt man diese sinnvoll ein?

    In diesem Kurs werden diese und weitere spannende Fragen beantwortet. Die Teilnehmer lernen am 
    praktischen Beispiel die Standard-APIs sinnvoll einzusetzen, um besseren Code zu schreiben. 
  featuredImage: TODO   

- name: 'JavaFX for beginners'
  trainers: ['hendrik', 'gerrit']
  summary: >
    An praktischen Beispielen lernen die Teilnehmer, wie sie mittels JavaFX sowohl grafisch 
    anspruchsvolle Benutzeroberflächen als auch nachhaltige Business- Anwendungen entwickeln.
  featuredImage: TODO   

- name: 'JavaFX für anspruchsvolle Benutzeroberflächen'
  trainers: ['hendrik', 'gerrit']
  summary: >
    In diesem Kurs lernen die Teilnehmer, wie sie mit den unterschiedlichen JavaFX APIs moderne 
    Benutzeroberflächen mit maximaler User Experience erstellen.
  featuredImage: TODO   

- name: 'JavaFX enterprise'
  trainers: ['hendrik']
  summary: >
    Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim 
    placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed 
    diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi 
    enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip 
    ex ea commodo consequat.
  featuredImage: TODO   